project:
  type: website
  output-dir: docs

website:
  title: "solidworks_git"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
    - section: "Excellent Design"
      contents:
      - excellent_pole.qmd
      - excellent_rectangle.qmd
      - excellent_assembly.qmd


format:
  html:
    theme: litera
    css: styles.css
    toc: true
    html-math-method: katex



